=== joaoflores99/AcademicProjects-ISEP-/ISEP/Year2/2Semestre/LPROG/Cartaz da queima/Cartaz.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:complexType name="TipoArtista">
		<xs:attribute name="nome" use="required" type="xs:string"/>
		<xs:attribute name="url" use="optional" type="xs:anyURI"/>
		<xs:attribute name="horario" use="required" type="xs:string"/>
	</xs:complexType>

    <xs:simpleType name="TipoDiaSemana">
        <xs:restriction base="xs:ID">
            <xs:enumeration value="domingo"/>
            <xs:enumeration value="segunda"/>
            <xs:enumeration value="terca"/>
            <xs:enumeration value="quarta"/>
            <xs:enumeration value="quinta"/>
            <xs:enumeration value="sexta"/>
            <xs:enumeration value="sabado"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TipoNoite">
      	<xs:sequence>
			<xs:element name="artista" type="TipoArtista" minOccurs="2" maxOccurs="2"/>
		</xs:sequence>
		<xs:attribute name="de" use="required" type="TipoDiaSemana"/>
	</xs:complexType> 

    <xs:simpleType name="TipoAno">
        <xs:restriction base="xs:int">
            <xs:pattern value="20[012][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
	
	<xs:complexType name="TipoCartaz">
		<xs:sequence>
			<xs:element name="noite" type="TipoNoite" minOccurs="7" maxOccurs="7"/>
		</xs:sequence>
		<xs:attribute name="ano" use="required" type="TipoAno"/>
	</xs:complexType>
	
	<xs:element name="cartaz" type="TipoCartaz"/>

</xs:schema>

=== joaoflores99/AcademicProjects-ISEP-/ISEP/Year2/2Semestre/LPROG/Cartaz da queima/Cartaz.xml
<?xml version="1.0"?>

<?xml-stylesheet type="text/xsl" href="t4.xslt"?>

<cartaz ano="2019" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cartaz.xsd">
	<noite de="sabado">
		<artista nome="100AURA" horario="00:01"/>
		<artista nome="RUI VELOSO" url="https://ruiveloso.com.pt/" horario="02:00"/>
	</noite>
	<noite de="domingo">
		<artista nome="DEEJAY TELIO" horario="23:00"/>
		<artista nome="DAVID CARREIRA" horario="01:00"/>
	</noite>
	<noite de="segunda">
		<artista nome="MUNDO SEGUNDO E SAM THE KID" horario="23:00"/>
		<artista nome="RICHIE CAMPBELL" horario="01:00"/>
	</noite>
	<noite de="terca">
		<artista nome="INSERT COIN" horario="23:00"/>
		<artista nome="QUIM BARREIROS" horario="01:00"/>
	</noite>
	<noite de="quarta">
		<artista nome="DAVID FONSECA" horario="23:00"/>
		<artista nome="WET BED GANG" horario="01:00"/>
	</noite>
	<noite de="quinta">
		<artista nome="MASTIKSOUL" horario="23:00"/>
		<artista nome="LOST FREQUENCIES" url="https://lostfrequencies.com/" horario="01:00"/>
	</noite>
	<noite de="sexta">
		<artista nome="JIMMY P" url="https://twitter.com/OfficialJimmyP" horario="23:00"/>
		<artista nome="GABRIEL O PENSADOR" url="https://gabrielopensador.com.br/" horario="01:00"/>
	</noite>
</cartaz>
